version: '3.6'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - '5432:5432'
    volumes:
      - '${HOME}/docker/${APPLICATION_NAME}/db:/var/lib/postgresql/data'
